[workspace]
name = "dotfiles"
version = "0.2.0"
description = "Junyi's portable dotfiles project"

channels = ["conda-forge"]
platforms = ["osx-arm64", "linux-64"]

[environments]
dev = ["global", "local"]
all = ["global"]


[feature.local.dependencies]
python = ">=3.12"
pytest = "*"
rust = "*"
ty = "*"
ruff = "*"
jupyter = "*"


[feature.global.dependencies]
rage = "*"
exa = "*"
fd-find = "*"
ripgrep = "*"
pip = "*"

# lsp
harper = "*"
tinymist = "*"
bash-language-server = "*"
markdown-oxide = "*"
