[project]
name = "dotfiles"
version = "0.1.0"
description = "Junyi's portable dotfiles project"
readme = "README.md"
requires-python = "==3.12.*"
dependencies = [
    "aider-chat>=0.86.1",
]

[dependency-groups]
dev = [
    "basedpyright>=1.32.1",
    "jupyter>=1.1.1",
    "pytest>=8.4.2",
]
